# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem 'grpc', github: 'ganmacs/grpc', branch: 'trailrs-only-if-possible', submodules: true
gem 'grpc', github: 'ganmacs/grpc', branch: 'trailrs-only-if-possible-always-resource-exhausted', submodules: true
